version: '3.1'
services:
  stringsdb-db:
    image: 'mysql:8.0'
    container_name: 'stringsdb-db'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: 'always'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - '3306:3306'
    networks:
      - stringsdb-network

  stringsdb-app:
    image: maven:3.8.2-jdk-11
    container_name: 'stringsdb-app'
    command: tail -F /dev/null
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    ports:
      - '8081:8080'
    networks:
      - stringsdb-network

networks:
  stringsdb-network:
    driver: bridge
