spring:
  datasource:
    username: "db_user"
    password: "db_password"
    url: "jdbc:mysql://stringsdb-db:3306/stringsdb"

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: "UTC"
        ddl-auto: "update"
        dialect: "org.hibernate.dialect.MySQLDialect"
        current_session_context_class: "org.springframework.orm.hibernate5.SpringSessionContext"
